### ISSUE TITLE
Error while loading MySQL Database.

### ISSUE THREAD

**Issue by JulianOS132** [wizguin/slippers#1]
Hello, I am using XAMPP, PHP 7.3.8 and I am getting a problem while loading the server:
[World] Starting world 1
**[Database] Could not connect to MySQL database**

Can somebody solve this problem?

I am running the server at 127.0.0.1:6114.

**Comment by wizguin** [comment]
A few things:

- Make sure you've set up the database correctly
- Make sure you are actually running the MySQL server through XAMPP, aswell as the Apache server
- Make sure you're using the correct details for your database in the config/config.json file
- If you're using a fresh install of XAMPP then you probably won't have a password set, so try leaving the password blank
- If that doesn't work then you will need to set a password for the database, and then use that password in the config.json file
