### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by ralsei63** [wizguin/slippers#10]
hi, sorry to interrupt again this is already the tenth error I had, I fixed all the others alone, I turned on the server and when I logged into the game, the game didn't even identify the penguin and when I went to look at the cmd, the game was crashed... THE GAME LOADS INFINITLY
![image](https://user-images.githubusercontent.com/64289385/80517391-60f63980-895b-11ea-9574-6a480e2c25ed.png)

**Comment by wizguin** [comment]
Looks like it's not getting any login credentials, do you have login.php in the right place, and set up correctly?

**Comment by ralsei63** [comment]
yes

**Comment by wizguin** [comment]
Can I see the response of the login.php file, you can find it by going into the developer console, then into the network tab, then click login.php.

**Comment by ralsei63** [comment]
can i add you in another place, i need help fast, message here is annoying

**Comment by ralsei63** [comment]
like discord

**Comment by wizguin** [comment]
Yeah post your tag

**Comment by ralsei63** [comment]
ralsei63#2363
