### ISSUE TITLE
Buying things in the catalog doesn't decrase coins from your account and items disappear from your inventory after server close.

### ISSUE THREAD

**Issue by JulianOS132** [wizguin/slippers#12]
Hello,

I have seen this issue today, is it a bug, or it will be added in a newer release?

Kind regards,
JulianOS132

**Comment by wizguin** [comment]
> Buying things in the catalog doesn't decrase coins from your account

This isn't implemented

> items disappear from your inventory after server close.

This shouldn't happen, are there any errors on the console? Check this issue too since they seemed to have the same issue with items not saving: https://github.com/wizguin/slippers/issues/3

**Comment by JulianOS132** [comment]
> This shouldn't happen, are there any errors on the console? Check this issue too since they seemed to have the same issue with items not saving: #3

I figured it out - they disappear on the 2005 media server and client.
They work with the 2007 client very good and the items are saving.

> This isn't implemented

Also, when do you plan to add coin decreasing?

**Comment by wizguin** [comment]
> They work with the 2007 client very good and the items are saving.

Oh yeah that would be because the newer items don't exist on the 2005 client so they show up blank.

> Also, when do you plan to add coin decreasing?

It would be easy to implement but I'm not currently working on this as my main project.
