### ISSUE TITLE
Python World.py Error

### ISSUE THREAD

**Issue by NicolasCLMendes** [wizguin/slippers#14]
When opening "World.py" with python 3 or 2, this error outputs:

`[unixKernel htdocs]# python World.py 1 #RUNNING WITH PYTHON3 AS ROOT
[World] Starting world 1
Traceback (most recent call last):
  File "World.py", line 32, in <module>
    main()
  File "World.py", line 28, in main
    World(sys.argv[1], config)
  File "World.py", line 18, in __init__
    self.db = Database(config)
  File "/opt/lampp/htdocs/world/Database.py", line 13, in __init__
    engine = create_engine("mysql+mysqlconnector://{}:{}@{}/{}".format(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqlconnector.py", line 129, in dbapi
    from mysql import connector
ModuleNotFoundError: No module named 'mysql'

[unixKernel htdocs]# python2 World.py 1 RUNNING WITH PYTHON2 AS ROOT
Traceback (most recent call last):
  File "World.py", line 4, in <module>
    from Server import Server
  File "/opt/lampp/htdocs/Server.py", line 1, in <module>
    import asyncio
ImportError: No module named asyncio
`

How to make the scripts work fine?
All the pip requirements from .txt file was already installed successfully.

**Comment by wizguin** [comment]
Install this for python 3: pip install --upgrade mysql-connector-python

**Comment by NicolasCLMendes** [comment]
Installed with the pip install --upgrade mysql-connector-python:

```
[dreamdevourer@unixKernel ~]$ pip install --upgrade mysql-connector-python
Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.20-cp38-cp38-manylinux1_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 7.8 MB/s 
Collecting protobuf>=3.0.0
  Downloading protobuf-3.12.1-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 17.2 MB/s 
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3.8/site-packages (from protobuf>=3.0.0->mysql-connector-python) (46.1.3)
Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/lib/python3.8/site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.14.0)
Installing collected packages: protobuf, mysql-connector-python
Successfully installed mysql-connector-python-8.0.20 protobuf-3.12.1

```
But the issue still happens:

```
[dreamdevourer@unixKernel htdocs]$ sudo python3 World.py 1
[World] Starting world 1
Traceback (most recent call last):
  File "World.py", line 32, in <module>
    main()
  File "World.py", line 28, in main
    World(sys.argv[1], config)
  File "World.py", line 18, in __init__
    self.db = Database(config)
  File "/opt/lampp/htdocs/world/Database.py", line 13, in __init__
    engine = create_engine("mysql+mysqlconnector://{}:{}@{}/{}".format(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqlconnector.py", line 129, in dbapi
    from mysql import connector
ModuleNotFoundError: No module named 'mysql'
```

I can't understand the exact cause, after having installed with pip install --upgrade mysql-connector-python, the command "python World.py 1" seems to have worked, just giving a permission denied error, but even when using SUDO the problem persisted.

**Comment by NicolasCLMendes** [comment]
Oh I was able to start the World.py after stopping all 3 XAMPP's services and running "sudo python3 World.py 1", but when the script is running, it can't read mysql database due to not permit root, but the script needs root to run... And another problem is that when the script is running, Apache Server Cannot start, because the script is already using 127.0.0.1 with port 80, The opposite also happens, if the apache server is running and the World.py script is opened, it returns:

```
[dreamdevourer@unixKernel htdocs]$ sudo python3 World.py 1
[World] Starting world 1
[Database] Could not connect to MySQL database
(mysql.connector.errors.ProgrammingError) 1698 (28000): Access denied for user 'root'@'localhost'
(Background on this error at: http://sqlalche.me/e/f405)
[PluginManager] 9 plugins loaded
Traceback (most recent call last):
  File "World.py", line 32, in <module>
    main()
  File "World.py", line 28, in main
    World(sys.argv[1], config)
  File "World.py", line 22, in __init__
    super(World, self).__init__(config, world_id, self.users, self.db, self.handler)
  File "/opt/lampp/htdocs/Server.py", line 16, in __init__
    self.server = self.loop.run_until_complete(self.coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 80): address already in use

```

The screenshot I put [here](https://i.imgur.com/ZBbowh0.png) shows what is happening.

**Comment by wizguin** [comment]
First make sure you have a password setup/are using the correct password for your database. Python shouldn't be using port 80 either, change it to something else.

**Comment by NicolasCLMendes** [comment]
It seems that I missed the step of config.json, a very important part, putting the door and the exact password were the errors. Everything worked now, Thanks! Did you know where to find newer versions of CP on a CDN?

**Comment by wizguin** [comment]
Check out https://github.com/solero

**Comment by NicolasCLMendes** [comment]
Thanks for the help.
