### ISSUE TITLE
Rooms appear pixelated, only interactive objects are high quality.

### ISSUE THREAD

**Issue by JulianOS132** [wizguin/slippers#15]
I have seen something like that:
![image](https://user-images.githubusercontent.com/51170759/83000915-4c18ce80-a00b-11ea-90d2-ec4f0ee84de9.png)

And i have another question,
Will you make a media server for 2009?

**Comment by wizguin** [comment]
This is how these rooms are meant to look, they're only designed to be viewed on a small screen. You can use room swfs from 2007-2008 to fix that. If you're looking for newer versions of the game (2009+) then check out https://github.com/solero.
