### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by klaiu228** [wizguin/slippers#18]
Hi! im new on the cpps emulator community and 
I think I did everything right, the server seems to connect, but I can't get into the game
see the pic: https://imgur.com/a/VIgyWmg

if you want, see if i configured something wrong: 
https://imgur.com/a/HBlvCFR
https://imgur.com/a/w5Ev3zT
https://imgur.com/a/eRSdwbU
https://imgur.com/a/OEwJw89

excuse me if i'm bothering you and please let me know!

**Comment by klaiu228** [comment]
P.S: im using the 2005 client.

**Comment by klaiu228** [comment]
Sorry if I'm interrupting you, I managed to solve that problem but another one came:
https://imgur.com/a/Lxx7kAc

you know how to solve it?

**Comment by wizguin** [comment]
This is an issue with your database setup, you either have the wrong password in your config file or don't have a password set at all.

**Comment by klaiu228** [comment]
Hello! sorry for interrupting you again, i managed to connected to the database successfully, but i went back to the first mistake, would you know how to fix it?

**Comment by wizguin** [comment]
Sorry for the late response, did you manage to fix this?

**Comment by klaiu228** [comment]
Hi! sorry for the late response, i restored my computer and did not install the files again :v.Well, thanks for helping me so far!
