### ISSUE TITLE
Issue with login.php "Notice: Undefined index: Username in C:\xampp\htdocs\php\login.php on line 10"?

### ISSUE THREAD

**Issue by LushPineapple29** [wizguin/slippers#24]
Currently at the moment, I am unable to connect to my own servers, I believe it has to do with login.php spewing out this.
"Notice: Undefined index: Username in C:\xampp\htdocs\php\login.php on line 10 &e=100"
I am unsure what to do, any help is appreciated!

**Comment by wizguin** [comment]
I'm not sure why this would happen. Username is posted from the chat swf to the php script when you login, which version of the game are you using?

**Comment by LushPineapple29** [comment]
I'm using the 2005 client.

**Comment by LushPineapple29** [comment]
> I'm not sure why this would happen. Username is posted from the chat swf to the php script when you login, which version of the game are you using?

I am using the 2005 client?

**Comment by LushPineapple29** [comment]
To just be exact, This is the first time I've ever used Slippers. So I could be messing up on the installation process.

**Comment by LushPineapple29** [comment]
Hey there!
So it seems the issue just went away, but a WHOLE new issue just came up.
`
Notice: Undefined index: items in C:\xampp\htdocs\php\login.php on line 21

Notice: Undefined index: pin in C:\xampp\htdocs\php\login.php on line 36

Notice: Undefined index: background in C:\xampp\htdocs\php\login.php on line 37
&s=0&rt=0&str=0&crumb=1|User|4|0|0|0|0|0|0|||0|0|0|1|0&il=&c=10000&bl=&nl=&k1=SeMBxfklcAQ3MTX&ed=86400&jd=2018-1-1`

I'm sure this is related to the database, I'm also using the default test account.

**Comment by wizguin** [comment]
I'm surprised nobody mentioned this before. I updated login.php, let me know if it works for you

**Comment by LushPineapple29** [comment]
I'll try it out now!

**Comment by LushPineapple29** [comment]
The server doesn't work, but login.php does!
Thanks for the help, I'll open a different issue soon if i have any more problems!
