### ISSUE TITLE
"[PluginManager] Error handling event: login {'msg': {'@t': 'sys', 'body': {'@action': 'login', '@r': '0', 'login': {'@z': 'w1', 'nick': None, 'pword': '0'}}}} Error: 'NoneType' object has no attribute 'lower'"

### ISSUE THREAD

**Issue by LushPineapple29** [wizguin/slippers#26]
I have set up a server, but when I try connecting from other clients within my home network, The console says
`"[PluginManager] Error handling event: login {'msg': {'@t': 'sys', 'body': {'@action': 'login', '@r': '0', 'login': {'@z': 'w1', 'nick': None, 'pword': '0'}}}}
Error: 'NoneType' object has no attribute 'lower'"`
I have tried modifying the config files and other stuff, Help would be appreciated.
Thanks!

**Comment by wizguin** [comment]
How have you set this up? It looks like you can connect to the server but it isn't receiving a username and password. What does the response from login.php look like?

**Comment by LushPineapple29** [comment]
> How have you set this up? It looks like you can connect to the server but it isn't receiving a username and password. What does the response from login.php look like?

I modified config, setup and login.php.
The response from the server is
`
Warning: Packets out of order. Expected 0 received 1. Packet size=79 in C:\xamppnew\htdocs\php\login.php on line 13

Warning: mysqli::__construct(): MySQL server has gone away in C:\xamppnew\htdocs\php\login.php on line 13

Warning: mysqli::__construct(): Error while reading greeting packet. PID=105872 in C:\xamppnew\htdocs\php\login.php on line 13

Warning: mysqli::__construct(): (HY000/2006): MySQL server has gone away in C:\xamppnew\htdocs\php\login.php on line 13
&e=0
`

**Comment by wizguin** [comment]
I don't have a second computer to test this, but make sure you're connecting to the host computer's local address and not localhost in login.php, otherwise you won't be able to connect to the sql server. Run ipconfig in cmd and look for IPv4 Address. https://stackoverflow.com/a/14641123/

If you did that and it still doesn't work then you probably need to set permissions, this should help: https://stackoverflow.com/a/27170813/ Create a second user instead of using root if you're worried about security, but this should be fine for just localhost.

**Comment by LushPineapple29** [comment]
I'll check it out.

**Comment by LushPineapple29** [comment]
> I don't have a second computer to test this, but make sure you're connecting to the host computer's local address and not localhost in login.php, otherwise you won't be able to connect to the sql server. Run ipconfig in cmd and look for IPv4 Address. https://stackoverflow.com/a/14641123/
> 
> If you did that and it still doesn't work then you probably need to set permissions, this should help: https://stackoverflow.com/a/27170813/ Create a second user instead of using root if you're worried about security, but this should be fine for just localhost.

I'm still having issues.
But, Instead of the previous error in console, now it just prints `<msg t='sys'><body action='verChk' r='0'><ver v='097' /></body></msg>`.

**Comment by wizguin** [comment]
Can you still connect to the game when using the host machine?

**Comment by LushPineapple29** [comment]
> Can you still connect to the game when using the host machine?

I've tried, It seems no.

**Comment by wizguin** [comment]
And login.php is sending the correct data?

**Comment by LushPineapple29** [comment]
> And login.php is sending the correct data?
Not for the host or the other computer.

**Comment by wizguin** [comment]
Can you show me what the response from login.php looks like now?

**Comment by LushPineapple29** [comment]
Warning: Packets out of order. Expected 0 received 1. Packet size=79 in C:\xamppnew\htdocs\php\login.php on line 13

Warning: mysqli::__construct(): MySQL server has gone away in C:\xamppnew\htdocs\php\login.php on line 13

Warning: mysqli::__construct(): Error while reading greeting packet. PID=105872 in C:\xamppnew\htdocs\php\login.php on line 13

Warning: mysqli::__construct(): (HY000/2006): MySQL server has gone away in C:\xamppnew\htdocs\php\login.php on line 13
&e=0

> Can you show me what the response from login.php looks like now?

**Comment by LushPineapple29** [comment]
> Can you show me what the response from login.php looks like now?

I've fixed login.php, but it now won't connect to the server.
It only just reports with
```<policy-file-request/>
<msg t='sys'><body action='verChk' r='0'><ver v='097' /></body></msg>```

**Comment by LushPineapple29** [comment]
I've gotten everything to work, Thank you so much!
If I have any more issues, I'll be sure to report them!
Thanks again!

**Comment by CrazyCSIW6** [comment]
how?
