### ISSUE TITLE
Issues with 2005/2007

### ISSUE THREAD

**Issue by Genko-H** [wizguin/slippers#3]
Alright, so i have so many problems with slippers. The reigster wont work, the igloo wont work, when you wear item and you log out they wont save on your skin on inventory. How do i fix this? Im hosting it on localhost btw

**Comment by wizguin** [comment]
Those first two issues aren't implemented yet:
- If you want you can just make a register form with php/html.
- Old igloo/igloo editor swf files are lost forever unfortunately so someone would have to recreate them.

Your items should save, check the database and see if items are being updated for players, the likely issue is that you haven't downloaded clothing - as my media-server doesn't include clothing to save space. You can find a media-server with clothing here: https://icer.ink/.

**Comment by Genko-H** [comment]
> Those first two issues aren't implemented yet:
> 
> * If you want you can just make a register form with php/html.
> * Old igloo/igloo editor swf files are lost forever unfortunately so someone would have to recreate them.
> 
> Your items should save, check the database and see if items are being updated for players, the likely issue is that you haven't downloaded clothing - as my media-server doesn't include clothing to save space. You can find a media-server with clothing here: https://icer.ink/.

I found the problem, it's not updating the items that the player wears ex color remains 0 , head remains 0, only the inventory updates

**Comment by Genko-H** [comment]
How do i make it update the items in the users table

**Comment by wizguin** [comment]
Do you get any errors when you try to wear clothing? Make sure you're closing the playercard because that is when the update_player function runs:

https://github.com/wizguin/slippers/blob/5e0c8f3250dcf5c8fd657e4e6aad2e601ff65754/plugins/items/Items.py#L38-L62
