### ISSUE TITLE
Not able to Connect on Other Devices

### ISSUE THREAD

**Issue by CraftedRllRl** [wizguin/slippers#42]
I've port forwarded my Slippers Server to ngrok, however eveytime I or any other person try to join there is an error.
The error is as follows:
"Was not able to connect to the server
Please click to learn more."
There is no error in the Server or Logs.

**Comment by CraftedRllRl** [comment]
Do note: I am able to join on The host device, but not any other

**Comment by superbird123** [comment]
No one is replying to the issues + It's impossible to get online servers unless you wanna pay for actual servers

**Comment by CraftedRllRl** [comment]
> No one is replying to the issues + It's impossible to get online servers unless you wanna pay for actual servers

I fixed it by changing setup.xml to the playit port lol (although it works half the time)

**Comment by CraftedRllRl** [comment]
No longer get this so
