### ISSUE TITLE
Webserver and py server working fine but cant join any CP server

### ISSUE THREAD

**Issue by Aberdeener** [wizguin/slippers#5]
hi
i have got everything working and i can sign in with user and test for username and password but it seems none of the club penguin servers are joinable. it loads forever and then gets the orange popup saying "was not able to connect to server". no output in console

any ideas?

**Comment by wizguin** [comment]
Make sure you have configured both the setup.xml file and the Login.py file.
- setup.xml should include your club penguin server config: https://github.com/wizguin/slippers/wiki/Configuration#setupxml
- Login.py should include the correct game version depending on what client you're using. https://github.com/wizguin/slippers/wiki/Configuration#setting-game-version
- Check the network tab on the developer console for any missing files.

**Comment by Aberdeener** [comment]
Another stupid issue: was navigating to localhost instead of 127.0.0.1 🤦‍♂ 
Hopefully this will help people in the future :P
