### ISSUE TITLE
asyncio

### ISSUE THREAD

**Issue by pedrohenriquenb** [wizguin/slippers#8]
It asks to import from **asyncio**, but it is not available anywhere.
Can you to help me configure and where to put all of the things to load the game?
Thank you!

**Comment by wizguin** [comment]
Latest Python 3 versions should come with asyncio, make sure you aren't using Python 3.3 or below.
The media server should already be setup and [this](https://github.com/wizguin/slippers/wiki/Installation#setting-up-the-media-server) will help you with that, if you have any specific problems with it let me know.

**Comment by pedrohenriquenb** [comment]
I'm trying to use python 3.8.2, but when I try to run the `python World.py 1` command using cmd and indicating the folder using `cd C:\xampp\htdocs`, it doesn't appear at all and leaves space to enter another command.

[Image of the problem](https://imgur.com/a/MHQwMhZ)

If you can, help me please...
Thank you so much!

**Comment by wizguin** [comment]
The server files, i.e everything in this repo, shouldn't be on your webserver. Make sure you're running the command in the same folder as World.py.

**Comment by pedrohenriquenb** [comment]
I'm doing it on localhost, so all the files are in the htdocs... I'm running everything in this folder where the World.py and Server.py files are, but that image problem happens.

[Image of the files](https://imgur.com/a/DLeZypA)

Thank you so much for helping me so far!

**Comment by wizguin** [comment]
That's strange, try just entering "python" and see what happens. You might have multiple versions installed:
![image](https://user-images.githubusercontent.com/16276645/80003214-99f46100-84b8-11ea-8b54-e19024ef575f.png)

Also, make sure your config.json is setup correctly, but I'm guessing it should be fine if you haven't touched it.

When you run World.py it should at the least print off this: [World] Starting world world_id

**Comment by pedrohenriquenb** [comment]
**wizguin, from now on, who will take my place for the questions will be ralsei63.
Thank you!
~Piter**

**Comment by ralsei63** [comment]
Hello Wizguin! I'm a friend of pedrohenriquenb and I have the same problem as him, I tried to connect the game with python 3.8.2 and PATH and even python gives the same error, can you help me? Thank you! (Yes, I tried to use the ''Python3'' command but the CMD said that the ''python3'' command did not exist) 
![image](https://user-images.githubusercontent.com/64289385/80263584-71f73000-8667-11ea-9173-3c27017c7330.png) 
![image](https://user-images.githubusercontent.com/64289385/80263597-7b809800-8667-11ea-8636-0be2b85078cb.png) 
![image](https://user-images.githubusercontent.com/64289385/80263606-83d8d300-8667-11ea-9674-342b92caac9b.png)

**Comment by wizguin** [comment]
How did you solve this @ralsei63 ?

**Comment by Sup-Sup123** [comment]
If asyncio is needed then shouldn't it be in the file named "requirements.txt"?

**Comment by wizguin** [comment]
> If asyncio is needed then shouldn't it be in the file named "requirements.txt"?

No because it's included in latest versions of Python 3

**Comment by Sup-Sup123** [comment]
Ok
