### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by ralsei63** [wizguin/slippers#9]
Hello @wizguin , how are you? I've been having an error with the codename of ''JSONDecodeError'', it happened after I solved the asyncio problem, I don't know anything about this error, could you help me? Thank you!
Screenshots: 
![image](https://user-images.githubusercontent.com/64289385/80324038-182c6c80-8805-11ea-8fd9-855920257297.png)

**Comment by wizguin** [comment]
Can I see your config.json file?

**Comment by ralsei63** [comment]
nvm, see my new error please, is already the tenth error
